### ISSUE TITLE
Suggestion: Change Title Color

### ISSUE THREAD

**Issue by RexJeff** [SamNie2027/github-crash-course#1]
I think it looks better if the main title is a bit more orange

the styling rule could be changed like this:

```css
h1 {
  color: #efa82e;
}
```
